var constants = {
	'SAVE_AUTHOR': 		'SAVE_AUTHOR',
	'AUTHOR_LOADED': 	'AUTHOR_LOADED',
	'AUTHORS_LOADED': 	'AUTHORS_LOADED',

	'SAVE_BOOK': 		'SAVE_BOOK',
 	'BOOK_LOADED': 		'BOOK_LOADED',
	'BOOKS_LOADED': 	'BOOKS_LOADED'
};

module.exports = constants;